# Site settings
title: Zonxin's Blog
description: > # this means to ignore newlines until "baseurl:"
  My Blog
baseurl: "" # the subpath of your site, e.g. /blog/
author: zonxin
url: "http://zonxin.github.io" # the base hostname & protocol for your site
github_username:  zonxin

# Build settings
permalink: post/:year/:month/:title
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge
gems:
    - jekyll-coffeescript
    - jekyll-paginate
# can not change in GitPage
lsi: false
safe: true
incremental: false
highlighter: rouge
gist: 
    noscript: false

