# Site settings
title: Zong's Blog
email: 0zonxin0@163.com
description: > # this means to ignore newlines until "baseurl:"
  My Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zonxin.github.io" # the base hostname & protocol for your site
github_username:  zonxin

# Build settings
permalink: post/:year/:month/:title
markdown: kramdown
